### ISSUE TITLE
Keycloak.X support. keycloak-metrics-spi 2.4.0 is not compatible with keycloak.x-14.0.0

### ISSUE THREAD

**Issue by irslon** [aerogear/keycloak-metrics-spi#107]
## Description
keycloak-metrics-spi is breaking startup of Keycloak.X 14.0.0.
Are there any plans to support Keycloak.X distribution?

## Actual Behavior
`2021-06-30 10:19:59,785 ERROR [org.key.cli.Picocli] (main) ERROR: Failed to start server using profile (dev).
2021-06-30 10:19:59,786 ERROR [org.key.cli.Picocli] (main) ERROR: Details:: java.lang.NoSuchMethodError: org.jboss.resteasy.spi.ResteasyProviderFactory.getContainerRequestFilterRegistry()Lorg/jboss/resteasy/core/interception/ContainerRequestFilterRegistry;
        at org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory.init(MetricsEndpointFactory.java:18)
        at org.keycloak.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:68)
        at org.keycloak.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:52)
        at org.keycloak.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:31)
        at org.keycloak.provider.quarkus.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:47)
        at org.keycloak.provider.quarkus.QuarkusLifecycleObserver_Observer_onStartupEvent_8292a286c9778cb4a07bc3314fcbfb61e7fe81a0.notify(QuarkusLifecycleObserver_Observer_onStartupEvent_8292a286c9778cb4a07bc331
4fcbfb61e7fe81a0.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:794)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at org.keycloak.cli.KeycloakMain.start(KeycloakMain.java:66)
        at org.keycloak.cli.KeycloakMain.start(KeycloakMain.java:62)
        at org.keycloak.cli.MainCommand.startDev(MainCommand.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.cli.KeycloakMain.parseAndRun(KeycloakMain.java:99)
        at org.keycloak.cli.KeycloakMain.main(KeycloakMain.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
`

## Environment

* Operating system: Windows 10
* Project Versions: 
  * Keycloak.X 14.0.0
  * keycloak-metrics-spi 2.4.0

## Steps to reproduce
1. Download [keycloak.x-preview-14.0.0.zip](https://github.com/keycloak/keycloak/releases/download/14.0.0/keycloak.x-preview-14.0.0.zip)
2. Download [keycloak-metrics-spi-2.4.0.jar](https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.4.0/keycloak-metrics-spi-2.4.0.jar)

3. Unzip keycloak.x-preview-14.0.0.zip
4. cd keycloak.x-14.0.0/
5. Copy keycloak-metrics-spi-2.4.0.jar into providers/
6. Run bin/kc.sh config
7. Run bin/kc.sh start-dev --verbose

**Comment by pb82** [comment]
Hmm, seems to be an incompatibility with Quarkus. It seems to be a problem when registering the metrics filter, so a first step to fix this issue on Quarkus could be to make it work without the metrics filter (you loose the request duration metrics). And then we need to look into how to support that.

**Comment by jangaraj** [comment]
Can this SPI use Open Telemetry (OTEL) instrumentation (https://github.com/open-telemetry/opentelemetry-java-instrumentation) and export metric via OTEL metric exporter (e.g. Prometheus) somehow?
Demo setup: https://github.com/jangaraj/keycloak-x-with-opentelemetry/

**Comment by semangard** [comment]
+1
