### ISSUE TITLE
Doesn't work with Keycloak 16

### ISSUE THREAD

**Issue by hypery2k** [aerogear/keycloak-metrics-spi#124]
## Description
metrics spi prevents Keycloak from Booting

## Expected Behavior
Normal boot

## Actual Behavior
Keycloak doesn't start:

```
07:03:10,616 FATAL [org.keycloak.services] (ServerService Thread Pool -- 52) Error during startup: java.lang.NoSuchMethodError: 'org.jboss.resteasy.core.interception.ContainerRequestFilterRegistry org.jboss.resteasy.spi.ResteasyProviderFactory.getContainerRequestFilterRegistry()'
	at deployment.keycloak-metrics-spi-2.5.3.jar//org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory.init(MetricsEndpointFactory.java:18)
	at org.keycloak.keycloak-services@16.0.0//org.keycloak.services.DefaultKeycloakSessionFactory.loadFactories(DefaultKeycloakSessionFactory.java:297)
	at org.keycloak.keycloak-services@16.0.0//org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:110)
	at org.keycloak.keycloak-services@16.0.0//org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:233)
	at org.keycloak.keycloak-services@16.0.0//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:124)
	at org.keycloak.keycloak-wildfly-extensions@16.0.0//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
	at org.keycloak.keycloak-services@16.0.0//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

```

## Environment

* Operating system: Linux with Docker, using latest Keycloak 16 Image with SPI added

**Comment by jonathanvila** [comment]
After some investigation these are my findings : 
* Keycloak 15.1.1 depends on Wildfly 23.0.2 that brings RestEasy v3
* Keycloak 16.0.0 depends on Wildfly 25.0.1 that brings RestEasy v4
* RestEasy v3 contains ResteasyProviderFactory class with an implemented method getContainerRequestFilterRegistry
* RestEasy v4 contains ResteasyProviderFactory class with an **abstract** method getContainerRequestFilterRegistry

That should be the problem , the change to abstract.

**Comment by pb82** [comment]
@jonathanvila thanks for the thorough investigation. #120 targets Keycloak 15, but includes a fix that should make in work on RestEasy 3 and 4. It's different than your suggested solution though. 

If you get a chance to try the new release (2.5.3) with this fix on Keycloak 16, that would be very appreciated!

**Comment by joggeli34** [comment]
It work for me with keycloak 16.1.0 and SPI 2.5.3, thanks

**Comment by hypery2k** [comment]
can confirm that it's working with Keycloak 15.0.2 and 16.1.0
