### ISSUE TITLE
i cant open the metrics endpoint in ha setting

### ISSUE THREAD

**Issue by dbagarozza** [aerogear/keycloak-metrics-spi#47]
## Description

i dont know if this is a issue, when i try to open the endpoint metrics in HA Keycloak Settings. I get the following error:

12:03:52,346 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7600]-5,null,null) JGRP000006: failed accepting connection from peer: java.net.SocketException: :7600: BaseServer.TcpConnection.readPeerAddress(): cookie sent by /:57222 does not match own cookie; terminating connection
        at org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:242)
        at org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:53)
        at org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:126)
        at org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:111)
        at org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
        at java.lang.Thread.run(Thread.java:748)

some ideas?  :)

**Comment by pb82** [comment]
@dbagarozza when you say `HA Keycloak Settings`, do you mean you are running multiple instances of keycloak behind a load balancer?

**Comment by dbagarozza** [comment]
yes :)
